spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    instance-id: ${spring.application.name}:${random.uuid}:${server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.instance-id}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    com.netflix.eureka: info
    com.netflix.discovery: info

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true