spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  profiles:
    #    Used to specify the active profile(s) for the local Spring Boot application.
    #    this will activate the corresponding spring.cloud.config.profile value
    active: dev
  application:
    name: api-gateway-service
#  config:
#    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      enabled: false
      name: ${spring.application.name}, application
      uri: http://localhost:8888
      # pull list of .yml and apply properties file based on spring.profiles.active
      profile: dev, prod
      fail-fast: true
#      discovery:
#        enabled: on
#        service-id: configuration-service